/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\个人项目\\VuePress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0cce09a8",
    path: "/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cce09a8").then(next)
    },
  },
  {
    name: "v-4eba5434",
    path: "/Other/Gzip.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4eba5434").then(next)
    },
  },
  {
    name: "v-3722c634",
    path: "/Cli/mock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3722c634").then(next)
    },
  },
  {
    name: "v-ecede768",
    path: "/ES6/proxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ecede768").then(next)
    },
  },
  {
    name: "v-49b24be5",
    path: "/Timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49b24be5").then(next)
    },
  },
  {
    path: "/Timeline/index.html",
    redirect: "/Timeline/"
  },
  {
    name: "v-ce98dc3c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ce98dc3c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-727310f7",
    path: "/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-727310f7").then(next)
    },
  },
  {
    path: "/Vue/Vue2 Diff算法解析.html",
    redirect: "/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html"
  },
  {
    path: "/Vue/Vue2 Diff算法解析.html",
    redirect: "/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html"
  },
  {
    name: "v-63acc4ea",
    path: "/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63acc4ea").then(next)
    },
  },
  {
    path: "/Vue/Vue3 架构搭建.html",
    redirect: "/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/Vue/Vue3 架构搭建.html",
    redirect: "/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-8b2cbb16",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b2cbb16").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-667bb668",
    path: "/tags/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-667bb668").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tags/ES6/index.html",
    redirect: "/tags/ES6/"
  },
  {
    name: "v-2aeea536",
    path: "/tags/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2aeea536").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tags/js/index.html",
    redirect: "/tags/js/"
  },
  {
    name: "v-ea7abf1a",
    path: "/tags/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ea7abf1a").then(next)
    },
    meta: {"pid":"tags","id":"前端"}
  },
  {
    path: "/tags/前端/index.html",
    redirect: "/tags/前端/"
  },
  {
    name: "v-7ebe3c06",
    path: "/tags/架构/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7ebe3c06").then(next)
    },
    meta: {"pid":"tags","id":"架构"}
  },
  {
    path: "/tags/架构/index.html",
    redirect: "/tags/架构/"
  },
  {
    name: "v-6b3c2d84",
    path: "/tags/mock/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6b3c2d84").then(next)
    },
    meta: {"pid":"tags","id":"mock"}
  },
  {
    path: "/tags/mock/index.html",
    redirect: "/tags/mock/"
  },
  {
    name: "v-669281ea",
    path: "/tags/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-669281ea").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tags/vue/index.html",
    redirect: "/tags/vue/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]