/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\study\\VuePress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4e2767bf",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e2767bf").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6074000b",
    path: "/%E5%85%B6%E4%BB%96/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6074000b").then(next)
    },
  },
  {
    path: "/其他/入职随笔.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94.html"
  },
  {
    path: "/其他/入职随笔.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94.html"
  },
  {
    name: "v-723ad65c",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-723ad65c").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-6662c6db",
    path: "/%E5%89%8D%E7%AB%AF/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6662c6db").then(next)
    },
  },
  {
    path: "/前端/ES6/promise.html",
    redirect: "/%E5%89%8D%E7%AB%AF/ES6/promise.html"
  },
  {
    path: "/前端/ES6/promise.html",
    redirect: "/%E5%89%8D%E7%AB%AF/ES6/promise.html"
  },
  {
    name: "v-08bbe002",
    path: "/%E5%85%B6%E4%BB%96/%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08bbe002").then(next)
    },
  },
  {
    path: "/其他/技术选型.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html"
  },
  {
    path: "/其他/技术选型.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html"
  },
  {
    name: "v-0d19ce16",
    path: "/%E5%89%8D%E7%AB%AF/ES6/proxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d19ce16").then(next)
    },
  },
  {
    path: "/前端/ES6/proxy.html",
    redirect: "/%E5%89%8D%E7%AB%AF/ES6/proxy.html"
  },
  {
    path: "/前端/ES6/proxy.html",
    redirect: "/%E5%89%8D%E7%AB%AF/ES6/proxy.html"
  },
  {
    name: "v-35806eed",
    path: "/%E5%89%8D%E7%AB%AF/%E6%9E%B6%E6%9E%84/mock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35806eed").then(next)
    },
  },
  {
    path: "/前端/架构/mock.html",
    redirect: "/%E5%89%8D%E7%AB%AF/%E6%9E%B6%E6%9E%84/mock.html"
  },
  {
    path: "/前端/架构/mock.html",
    redirect: "/%E5%89%8D%E7%AB%AF/%E6%9E%B6%E6%9E%84/mock.html"
  },
  {
    name: "v-6c086f68",
    path: "/%E5%85%B6%E4%BB%96/%E7%BB%8F%E9%AA%8C%E6%B1%87%E6%80%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c086f68").then(next)
    },
  },
  {
    path: "/其他/经验汇总.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E7%BB%8F%E9%AA%8C%E6%B1%87%E6%80%BB.html"
  },
  {
    path: "/其他/经验汇总.html",
    redirect: "/%E5%85%B6%E4%BB%96/%E7%BB%8F%E9%AA%8C%E6%B1%87%E6%80%BB.html"
  },
  {
    name: "v-edcdfa52",
    path: "/%E5%89%8D%E7%AB%AF/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edcdfa52").then(next)
    },
  },
  {
    path: "/前端/Vue/Vue3 架构搭建.html",
    redirect: "/%E5%89%8D%E7%AB%AF/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/前端/Vue/Vue3 架构搭建.html",
    redirect: "/%E5%89%8D%E7%AB%AF/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-1a0b59b8",
    path: "/%E5%89%8D%E7%AB%AF/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a0b59b8").then(next)
    },
  },
  {
    path: "/前端/Vue/Vue2 Diff算法解析.html",
    redirect: "/%E5%89%8D%E7%AB%AF/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html"
  },
  {
    path: "/前端/Vue/Vue2 Diff算法解析.html",
    redirect: "/%E5%89%8D%E7%AB%AF/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-146949ae",
    path: "/tags/其他/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-146949ae").then(next)
    },
    meta: {"pid":"tags","id":"其他"}
  },
  {
    path: "/tags/其他/index.html",
    redirect: "/tags/其他/"
  },
  {
    name: "v-19941d82",
    path: "/tags/入职随笔/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19941d82").then(next)
    },
    meta: {"pid":"tags","id":"入职随笔"}
  },
  {
    path: "/tags/入职随笔/index.html",
    redirect: "/tags/入职随笔/"
  },
  {
    name: "v-667bb668",
    path: "/tags/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-667bb668").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tags/ES6/index.html",
    redirect: "/tags/ES6/"
  },
  {
    name: "v-2aeea536",
    path: "/tags/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2aeea536").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tags/js/index.html",
    redirect: "/tags/js/"
  },
  {
    name: "v-ea7abf1a",
    path: "/tags/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ea7abf1a").then(next)
    },
    meta: {"pid":"tags","id":"前端"}
  },
  {
    path: "/tags/前端/index.html",
    redirect: "/tags/前端/"
  },
  {
    name: "v-b0bd68ee",
    path: "/tags/项目开发/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b0bd68ee").then(next)
    },
    meta: {"pid":"tags","id":"项目开发"}
  },
  {
    path: "/tags/项目开发/index.html",
    redirect: "/tags/项目开发/"
  },
  {
    name: "v-7ebe3c06",
    path: "/tags/架构/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7ebe3c06").then(next)
    },
    meta: {"pid":"tags","id":"架构"}
  },
  {
    path: "/tags/架构/index.html",
    redirect: "/tags/架构/"
  },
  {
    name: "v-6b3c2d84",
    path: "/tags/mock/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6b3c2d84").then(next)
    },
    meta: {"pid":"tags","id":"mock"}
  },
  {
    path: "/tags/mock/index.html",
    redirect: "/tags/mock/"
  },
  {
    name: "v-669281ea",
    path: "/tags/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-669281ea").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tags/vue/index.html",
    redirect: "/tags/vue/"
  },
  {
    name: "v-7fc479ec",
    path: "/categories/其他/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7fc479ec").then(next)
    },
    meta: {"pid":"categories","id":"其他"}
  },
  {
    path: "/categories/其他/index.html",
    redirect: "/categories/其他/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]