/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "秃头披风侠",
  "description": "你好，世界！",
  "base": "/",
  "headTags": [
    [
      "script",
      {
        "charset": "utf-8",
        "src": "/js/custom.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "ES6",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/ES6/promise.html",
      "relativePath": "ES6/promise.md",
      "key": "v-0cce09a8",
      "path": "/ES6/promise.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "7/31/2023, 6:34:29 PM",
      "lastUpdatedTimestamp": 1690799669000
    },
    {
      "title": "Gzip",
      "frontmatter": {
        "readingShow": "top"
      },
      "regularPath": "/Other/Gzip.html",
      "relativePath": "Other/Gzip.md",
      "key": "v-4eba5434",
      "path": "/Other/Gzip.html",
      "headers": [
        {
          "level": 3,
          "title": "Gzip",
          "slug": "gzip"
        }
      ]
    },
    {
      "title": "Mock",
      "frontmatter": {
        "title": "Mock",
        "date": "2023-07-26T12:44:15.000Z",
        "sidebar": "auto",
        "isShowComment": true,
        "tags": [
          "架构",
          "mock",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/Cli/mock.html",
      "relativePath": "Cli/mock.md",
      "key": "v-3722c634",
      "path": "/Cli/mock.html",
      "headers": [
        {
          "level": 2,
          "title": "我为什么需要mock",
          "slug": "我为什么需要mock"
        },
        {
          "level": 2,
          "title": "为什么选择MockJs",
          "slug": "为什么选择mockjs"
        },
        {
          "level": 2,
          "title": "MockJs安装与基本用法",
          "slug": "mockjs安装与基本用法"
        },
        {
          "level": 2,
          "title": "Mock的封装",
          "slug": "mock的封装"
        },
        {
          "level": 2,
          "title": "Mock的增删改查",
          "slug": "mock的增删改查"
        }
      ],
      "excerpt": "<div class=\"custom-block danger\">\n<p>axios + mock</p>\n</div>\n"
    },
    {
      "title": "Proxy",
      "frontmatter": {
        "title": "Proxy",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "ES6",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/ES6/proxy.html",
      "relativePath": "ES6/proxy.md",
      "key": "v-ecede768",
      "path": "/ES6/proxy.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "7/31/2023, 6:34:29 PM",
      "lastUpdatedTimestamp": 1690799669000
    },
    {
      "title": "Time Line",
      "frontmatter": {
        "isTimeLine": true,
        "sidebar": false,
        "isComment": false,
        "readingShow": "top"
      },
      "regularPath": "/Timeline/",
      "relativePath": "Timeline/README.md",
      "key": "v-49b24be5",
      "path": "/Timeline/",
      "headers": [
        {
          "level": 2,
          "title": "Time Line",
          "slug": "time-line"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "殷冲的个人博客",
        "bgImage": "/img/5.jpg",
        "bgImageStyle": {
          "height": "350px"
        },
        "isShowTitleInHome": true,
        "actionText": "About Me",
        "actionLink": "/views/personalInfo/",
        "features": [
          {
            "title": "Who am I？",
            "details": "A programmer? A human being? Or a matter combination?"
          },
          {
            "title": "Where am I？",
            "details": "In a city? On earth? Or in a small part of space?"
          },
          {
            "title": "What am I gona do？",
            "details": "Work? Struggle? Or go to a destination I don't know?"
          }
        ],
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-ce98dc3c",
      "path": "/",
      "lastUpdated": "2/8/2023, 9:55:50 AM",
      "lastUpdatedTimestamp": 1675821350000
    },
    {
      "title": "Vue2 Diff算法解析",
      "frontmatter": {
        "title": "Vue2 Diff算法解析",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "vue",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
      "relativePath": "Vue/Vue2 Diff算法解析.md",
      "key": "v-727310f7",
      "path": "/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "7/31/2023, 6:34:29 PM",
      "lastUpdatedTimestamp": 1690799669000
    },
    {
      "title": "Vue3 架构搭建",
      "frontmatter": {
        "title": "Vue3 架构搭建",
        "date": "2023-05-04T12:44:15.000Z",
        "tags": [
          "vue",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
      "relativePath": "Vue/Vue3 架构搭建.md",
      "key": "v-63acc4ea",
      "path": "/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
      "lastUpdated": "7/31/2023, 6:34:29 PM",
      "lastUpdatedTimestamp": 1690799669000
    },
    {
      "title": "前端知识体系汇总",
      "frontmatter": {
        "title": "前端知识体系汇总",
        "date": "2023-07-31T00:00:00.000Z",
        "sidebar": "auto",
        "isTimeLine": false,
        "isShowComment": true,
        "readingShow": "top"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-8b2cbb16",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "知识体系总览",
          "slug": "知识体系总览"
        },
        {
          "level": 3,
          "title": "HTML",
          "slug": "html"
        },
        {
          "level": 3,
          "title": "CSS",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "JS + ES6",
          "slug": "js-es6"
        },
        {
          "level": 3,
          "title": "大厂面试类",
          "slug": "大厂面试类"
        },
        {
          "level": 2,
          "title": "项目实战",
          "slug": "项目实战"
        },
        {
          "level": 2,
          "title": "书籍推荐",
          "slug": "书籍推荐"
        }
      ],
      "lastUpdated": "7/31/2023, 6:34:29 PM",
      "lastUpdatedTimestamp": 1690799669000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/ES6/",
      "key": "v-667bb668",
      "path": "/tags/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/js/",
      "key": "v-2aeea536",
      "path": "/tags/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E5%89%8D%E7%AB%AF/",
      "key": "v-ea7abf1a",
      "path": "/tags/前端/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "架构 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E6%9E%B6%E6%9E%84/",
      "key": "v-7ebe3c06",
      "path": "/tags/架构/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "mock tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/mock/",
      "key": "v-6b3c2d84",
      "path": "/tags/mock/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/vue/",
      "key": "v-669281ea",
      "path": "/tags/vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "smoothScroll": true,
    "authorAvatar": "/avatar.png",
    "lastUpdated": "2023-02-07",
    "author": "殷冲",
    "startYear": "2023",
    "nav": [
      {
        "text": "Web",
        "link": "/guide/",
        "icon": "reco-eye"
      },
      {
        "text": "Vue",
        "link": "/Vue/",
        "icon": "reco-api",
        "items": [
          {
            "text": "Vue2 Diff算法解析",
            "link": "/Vue/Vue2 Diff算法解析"
          },
          {
            "text": "Vue3",
            "link": "/Vue/Vue3 架构搭建"
          }
        ]
      },
      {
        "text": "ES6",
        "link": "/ES6/",
        "icon": "reco-api",
        "items": [
          {
            "text": "promise",
            "link": "/ES6/promise"
          },
          {
            "text": "proxy",
            "link": "/ES6/proxy"
          }
        ]
      },
      {
        "text": "Cli",
        "link": "/Cli/",
        "icon": "reco-api",
        "items": [
          {
            "text": "mock",
            "link": "/Cli/mock"
          }
        ]
      },
      {
        "text": "Other",
        "link": "/Other/",
        "icon": "reco-faq",
        "items": [
          {
            "text": "Gzip",
            "link": "/Other/Gzip"
          }
        ]
      },
      {
        "text": "Timeline",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2,
    "search": true,
    "searchMaxSuggestions": 10,
    "cyberSecurityRecord": "沪公网安备 xxxxxxx号",
    "cyberSecurityLink": "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=xxx05177"
  }
}