/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "秃头披风侠",
  "description": "你好，世界！",
  "base": "/",
  "headTags": [
    [
      "script",
      {
        "charset": "utf-8",
        "src": "/js/custom.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "殷冲的个人博客",
        "bgImage": "/img/5.jpg",
        "bgImageStyle": {
          "height": "350px"
        },
        "isShowTitleInHome": true,
        "actionText": "About Me",
        "actionLink": "/views/personalInfo/",
        "features": [
          {
            "title": "Who am I？",
            "details": "A programmer? A human being? Or a matter combination?"
          },
          {
            "title": "Where am I？",
            "details": "In a city? On earth? Or in a small part of space?"
          },
          {
            "title": "What am I gona do？",
            "details": "Work? Struggle? Or go to a destination I don't know?"
          }
        ],
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4e2767bf",
      "path": "/",
      "lastUpdated": "2/8/2023, 9:55:50 AM",
      "lastUpdatedTimestamp": 1675821350000
    },
    {
      "title": "本站指南",
      "frontmatter": {
        "title": "本站指南",
        "date": "2022-06-06T00:00:00.000Z",
        "sidebar": "auto",
        "isTimeLine": false,
        "isShowComment": true,
        "readingShow": "top"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-723ad65c",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "知识体系总览",
          "slug": "知识体系总览"
        },
        {
          "level": 3,
          "title": "初级教程类",
          "slug": "初级教程类"
        },
        {
          "level": 3,
          "title": "高级框架类",
          "slug": "高级框架类"
        },
        {
          "level": 3,
          "title": "架构设计类",
          "slug": "架构设计类"
        },
        {
          "level": 3,
          "title": "大厂面试类",
          "slug": "大厂面试类"
        },
        {
          "level": 2,
          "title": "项目实战",
          "slug": "项目实战"
        },
        {
          "level": 2,
          "title": "书籍推荐",
          "slug": "书籍推荐"
        }
      ],
      "lastUpdated": "2/7/2023, 11:10:19 AM",
      "lastUpdatedTimestamp": 1675739419000
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "title": "如何做好技术选型",
      "frontmatter": {
        "title": " 如何做好技术选型",
        "date": "2023-04-21T10:00:00.000Z",
        "isShowComment": true,
        "tags": [
          "其他",
          "项目开发"
        ],
        "categories": [
          "其他"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html",
      "relativePath": "其他/技术选型.md",
      "key": "v-08bbe002",
      "path": "/%E5%85%B6%E4%BB%96/%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "技术选型一定要与开发沟通",
          "slug": "技术选型一定要与开发沟通"
        },
        {
          "level": 3,
          "title": "选择成熟的技术",
          "slug": "选择成熟的技术"
        },
        {
          "level": 3,
          "title": "从业务、项目规模出发",
          "slug": "从业务、项目规模出发"
        },
        {
          "level": 3,
          "title": "先验证后使用",
          "slug": "先验证后使用"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"custom-block-title\">说明</p>\n<p>记录一下在开发时遇到的关于技术选型的问题，以及如何做好技术选型</p>\n</div>\n",
      "lastUpdated": "4/24/2023, 3:13:49 PM",
      "lastUpdatedTimestamp": 1682320429000
    },
    {
      "title": "入职随笔",
      "frontmatter": {
        "title": "入职随笔",
        "date": "2023-07-17T10:00:00.000Z",
        "isShowComment": true,
        "tags": [
          "其他",
          "入职随笔"
        ],
        "categories": [
          "其他"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94.html",
      "relativePath": "其他/入职随笔.md",
      "key": "v-6074000b",
      "path": "/%E5%85%B6%E4%BB%96/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"custom-block-title\">说明</p>\n<p>记录入职左邻的所思所想</p>\n</div>\n",
      "lastUpdated": "7/17/2023, 6:42:22 PM",
      "lastUpdatedTimestamp": 1689590542000
    },
    {
      "title": "记录一些开发时的想法",
      "frontmatter": {
        "title": "记录一些开发时的想法",
        "date": "2023-04-23T10:00:00.000Z",
        "isShowComment": true,
        "tags": [
          "其他",
          "项目开发"
        ],
        "categories": [
          "其他"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%85%B6%E4%BB%96/%E7%BB%8F%E9%AA%8C%E6%B1%87%E6%80%BB.html",
      "relativePath": "其他/经验汇总.md",
      "key": "v-6c086f68",
      "path": "/%E5%85%B6%E4%BB%96/%E7%BB%8F%E9%AA%8C%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 3,
          "title": "及时沟通，及时反馈",
          "slug": "及时沟通-及时反馈"
        },
        {
          "level": 3,
          "title": "合理的评估工时",
          "slug": "合理的评估工时"
        },
        {
          "level": 3,
          "title": "不要轻易的去否定他人",
          "slug": "不要轻易的去否定他人"
        },
        {
          "level": 3,
          "title": "了解业务，理解需求",
          "slug": "了解业务-理解需求"
        }
      ],
      "excerpt": "",
      "lastUpdated": "4/24/2023, 3:13:49 PM",
      "lastUpdatedTimestamp": 1682320429000
    },
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "ES6",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/ES6/promise.html",
      "relativePath": "前端/ES6/promise.md",
      "key": "v-6662c6db",
      "path": "/%E5%89%8D%E7%AB%AF/ES6/promise.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "3/4/2023, 6:31:03 PM",
      "lastUpdatedTimestamp": 1677925863000
    },
    {
      "title": "Proxy",
      "frontmatter": {
        "title": "Proxy",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "ES6",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/ES6/proxy.html",
      "relativePath": "前端/ES6/proxy.md",
      "key": "v-0d19ce16",
      "path": "/%E5%89%8D%E7%AB%AF/ES6/proxy.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "3/4/2023, 6:31:03 PM",
      "lastUpdatedTimestamp": 1677925863000
    },
    {
      "title": "Vue2 Diff算法解析",
      "frontmatter": {
        "title": "Vue2 Diff算法解析",
        "date": "2023-02-08T12:44:15.000Z",
        "tags": [
          "vue",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
      "relativePath": "前端/Vue/Vue2 Diff算法解析.md",
      "key": "v-1a0b59b8",
      "path": "/%E5%89%8D%E7%AB%AF/Vue/Vue2%20Diff%E7%AE%97%E6%B3%95%E8%A7%A3%E6%9E%90.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块</p>\n</div>\n",
      "lastUpdated": "3/4/2023, 6:31:03 PM",
      "lastUpdatedTimestamp": 1677925863000
    },
    {
      "title": "Vue3 架构搭建",
      "frontmatter": {
        "title": "Vue3 架构搭建",
        "date": "2023-05-04T12:44:15.000Z",
        "tags": [
          "vue",
          "js",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
      "relativePath": "前端/Vue/Vue3 架构搭建.md",
      "key": "v-edcdfa52",
      "path": "/%E5%89%8D%E7%AB%AF/Vue/Vue3%20%E6%9E%B6%E6%9E%84%E6%90%AD%E5%BB%BA.html",
      "lastUpdated": "5/10/2023, 3:35:10 PM",
      "lastUpdatedTimestamp": 1683704110000
    },
    {
      "title": "Mock",
      "frontmatter": {
        "title": "Mock",
        "date": "2023-07-26T12:44:15.000Z",
        "tags": [
          "架构",
          "mock",
          "前端"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E5%89%8D%E7%AB%AF/%E6%9E%B6%E6%9E%84/mock.html",
      "relativePath": "前端/架构/mock.md",
      "key": "v-35806eed",
      "path": "/%E5%89%8D%E7%AB%AF/%E6%9E%B6%E6%9E%84/mock.html",
      "headers": [
        {
          "level": 3,
          "title": "我为什么需要mock",
          "slug": "我为什么需要mock"
        },
        {
          "level": 3,
          "title": "为什么选择MockJs",
          "slug": "为什么选择mockjs"
        },
        {
          "level": 3,
          "title": "MockJs安装与基本用法",
          "slug": "mockjs安装与基本用法"
        },
        {
          "level": 3,
          "title": "Mock的封装",
          "slug": "mock的封装"
        }
      ],
      "excerpt": "<div class=\"custom-block danger\">\n<p>axios + mock</p>\n</div>\n"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "其他 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E5%85%B6%E4%BB%96/",
      "key": "v-146949ae",
      "path": "/tags/其他/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "项目开发 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91/",
      "key": "v-b0bd68ee",
      "path": "/tags/项目开发/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "入职随笔 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E5%85%A5%E8%81%8C%E9%9A%8F%E7%AC%94/",
      "key": "v-19941d82",
      "path": "/tags/入职随笔/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/ES6/",
      "key": "v-667bb668",
      "path": "/tags/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/js/",
      "key": "v-2aeea536",
      "path": "/tags/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E5%89%8D%E7%AB%AF/",
      "key": "v-ea7abf1a",
      "path": "/tags/前端/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/vue/",
      "key": "v-669281ea",
      "path": "/tags/vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "架构 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E6%9E%B6%E6%9E%84/",
      "key": "v-7ebe3c06",
      "path": "/tags/架构/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "mock tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/mock/",
      "key": "v-6b3c2d84",
      "path": "/tags/mock/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "其他 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%85%B6%E4%BB%96/",
      "key": "v-7fc479ec",
      "path": "/categories/其他/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "smoothScroll": true,
    "authorAvatar": "/avatar.png",
    "lastUpdated": "2023-02-07",
    "author": "殷冲",
    "startYear": "2023",
    "nav": [
      {
        "text": "本站指南",
        "link": "/guide/",
        "icon": "reco-eye"
      },
      {
        "text": "前端",
        "link": "/前端/",
        "icon": "reco-api",
        "items": [
          {
            "text": "Vue",
            "items": [
              {
                "text": "Vue2",
                "link": "/前端/Vue/Vue2 Diff算法解析"
              },
              {
                "text": "Vue3",
                "link": "/前端/Vue/Vue3 架构搭建"
              }
            ]
          },
          {
            "text": "ES6",
            "items": [
              {
                "text": "promise",
                "link": "/前端/ES6/promise"
              },
              {
                "text": "proxy",
                "link": "/前端/ES6/proxy"
              }
            ]
          },
          {
            "text": "架构 ",
            "items": [
              {
                "text": "mock",
                "link": "/前端/架构/mock"
              }
            ]
          }
        ]
      },
      {
        "text": "其他",
        "link": "/其他/",
        "icon": "reco-faq",
        "items": [
          {
            "text": "技术选型",
            "link": "/其他/技术选型"
          },
          {
            "text": "问题汇总",
            "link": "/其他/问题汇总"
          },
          {
            "text": "入职随笔",
            "link": "/其他/入职随笔"
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2,
    "search": true,
    "searchMaxSuggestions": 10,
    "cyberSecurityRecord": "沪公网安备 xxxxxxx号",
    "cyberSecurityLink": "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=xxx05177"
  }
}