/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "君哥聊编程",
  "description": "点赞、转发、收藏",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "君哥聊编程,vuepress,自建博客,君哥"
      }
    ],
    [
      "meta",
      {
        "name": "description",
        "content": "专属于自学者的在线学习平台,这里有编程领域最完善最「体系化的」Java学习视频、如果你是小白快加入我们一起学最全最「体系化的」java知识吧，官方交流QQ群：827553720"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "robots",
        "content": "all"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "君哥"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/css/style.css"
      }
    ],
    [
      "script",
      {
        "charset": "utf-8",
        "src": "/js/custom.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "粉丝的个人博客",
        "bgImage": "/img/5.jpg",
        "bgImageStyle": {
          "height": "350px"
        },
        "isShowTitleInHome": true,
        "actionText": "About Me",
        "actionLink": "/views/personalInfo/",
        "features": [
          {
            "title": "Who am I？",
            "details": "A programmer? A human being? Or a matter combination?"
          },
          {
            "title": "Where am I？",
            "details": "In a city? On earth? Or in a small part of space?"
          },
          {
            "title": "What am I gona do？",
            "details": "Work? Struggle? Or go to a destination I don't know?"
          }
        ],
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3ce27bdd",
      "path": "/"
    },
    {
      "title": "Java基础",
      "frontmatter": {
        "title": "Java基础",
        "date": "2100-05-01T12:44:15.000Z",
        "tags": [
          "面向对象",
          "JavaSE"
        ],
        "categories": [
          "java"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/java/javase.html",
      "relativePath": "技术文章/java/javase.md",
      "key": "v-0f85ec36",
      "path": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/java/javase.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是Java基础的摘要内容，<code>vuepress</code>提供的语法块，这部分内容会显示在首页，不信你去首页看看</p>\n<p><a href=\"https://ke.qq.com/course/5285550\" target=\"_blank\" rel=\"noopener noreferrer\">点击免费观看教学视频<OutboundLink/></a></p>\n</div>\n"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "title": "本站指南",
      "frontmatter": {
        "title": "本站指南",
        "date": "2022-06-06T00:00:00.000Z",
        "sidebar": "auto",
        "isTimeLine": false,
        "isShowComment": true,
        "readingShow": "top"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-b60b2820",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "知识体系总览",
          "slug": "知识体系总览"
        },
        {
          "level": 3,
          "title": "初级教程类",
          "slug": "初级教程类"
        },
        {
          "level": 3,
          "title": "高级框架类",
          "slug": "高级框架类"
        },
        {
          "level": 3,
          "title": "架构设计类",
          "slug": "架构设计类"
        },
        {
          "level": 3,
          "title": "大厂面试类",
          "slug": "大厂面试类"
        },
        {
          "level": 2,
          "title": "项目实战",
          "slug": "项目实战"
        },
        {
          "level": 2,
          "title": "书籍推荐",
          "slug": "书籍推荐"
        }
      ]
    },
    {
      "title": "前端基础",
      "frontmatter": {
        "title": "前端基础",
        "date": "2100-05-01T12:44:15.000Z",
        "tags": [
          "vue",
          "js"
        ],
        "categories": [
          "前端"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/vue/vue01.html",
      "relativePath": "技术文章/vue/vue01.md",
      "key": "v-24098ea5",
      "path": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/vue/vue01.html",
      "excerpt": "<div class=\"custom-block danger\"><p class=\"custom-block-title\">说明</p>\n<p>这是前端基础的摘要内容，<code>vuepress</code>提供的语法块，这部分内容会显示在首页，不信你去首页看看</p>\n<p><a href=\"https://ke.qq.com/course/5285550\" target=\"_blank\" rel=\"noopener noreferrer\">点击免费观看教学视频<OutboundLink/></a></p>\n</div>\n"
    },
    {
      "title": "分享生活",
      "frontmatter": {
        "title": " 分享生活",
        "date": "2200-05-01T12:44:15.000Z",
        "tags": [
          "生活",
          "分享生活"
        ],
        "categories": [
          "生活"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E7%94%9F%E6%B4%BB%E5%88%86%E4%BA%AB/life.html",
      "relativePath": "生活分享/life.md",
      "key": "v-472a77c8",
      "path": "/%E7%94%9F%E6%B4%BB%E5%88%86%E4%BA%AB/life.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"custom-block-title\">说明</p>\n<p>这是分享生活的摘要内容，<code>vuepress</code>提供的语法块，这部分内容会显示在首页，不信你去首页看看</p>\n<p><a href=\"https://ke.qq.com/course/5285550\" target=\"_blank\" rel=\"noopener noreferrer\">点击免费观看教学视频<OutboundLink/></a></p>\n</div>\n"
    },
    {
      "title": "Java零基础学习路线",
      "frontmatter": {
        "title": "Java零基础学习路线",
        "date": "2022-08-08T00:00:00.000Z",
        "sidebarDepth": 2,
        "categories": [
          "Java基础"
        ],
        "tags": [
          "Java基础",
          "零基础"
        ],
        "author": "君哥",
        "publish": true,
        "readingShow": "top"
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/",
      "relativePath": "技术文章/README.md",
      "key": "v-72c750ef",
      "path": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/",
      "headers": [
        {
          "level": 2,
          "title": "学习之路",
          "slug": "学习之路"
        }
      ],
      "excerpt": ""
    },
    {
      "title": "Java高级",
      "frontmatter": {
        "title": "Java高级",
        "date": "2100-05-01T12:44:15.000Z",
        "tags": [
          "Spring",
          "SpringBoot"
        ],
        "categories": [
          "java"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/java%E9%AB%98%E7%BA%A7/javaee.html",
      "relativePath": "技术文章/java高级/javaee.md",
      "key": "v-ca9a1562",
      "path": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/java%E9%AB%98%E7%BA%A7/javaee.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"custom-block-title\">说明</p>\n<p>这是Java高级的摘要内容，<code>vuepress</code>提供的语法块，这部分内容会显示在首页，不信你去首页看看</p>\n<p><a href=\"https://ke.qq.com/course/5285550\" target=\"_blank\" rel=\"noopener noreferrer\">点击免费观看教学视频<OutboundLink/></a></p>\n</div>\n"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "面向对象 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/",
      "key": "v-16454405",
      "path": "/tags/面向对象/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaSE tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/JavaSE/",
      "key": "v-3a90ac7a",
      "path": "/tags/JavaSE/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/vue/",
      "key": "v-669281ea",
      "path": "/tags/vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/js/",
      "key": "v-2aeea536",
      "path": "/tags/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "生活 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E7%94%9F%E6%B4%BB/",
      "key": "v-31b3711a",
      "path": "/tags/生活/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "分享生活 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E5%88%86%E4%BA%AB%E7%94%9F%E6%B4%BB/",
      "key": "v-33a24f30",
      "path": "/tags/分享生活/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Java基础 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/Java%E5%9F%BA%E7%A1%80/",
      "key": "v-2a5adf98",
      "path": "/tags/Java基础/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "零基础 tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/%E9%9B%B6%E5%9F%BA%E7%A1%80/",
      "key": "v-e03f2858",
      "path": "/tags/零基础/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Spring tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/Spring/",
      "key": "v-300d2181",
      "path": "/tags/Spring/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "SpringBoot tags",
        "readingShow": "top"
      },
      "regularPath": "/tags/SpringBoot/",
      "key": "v-3aee5baf",
      "path": "/tags/SpringBoot/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "java categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/java/",
      "key": "v-62faafef",
      "path": "/categories/java/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "生活 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E7%94%9F%E6%B4%BB/",
      "key": "v-711f6636",
      "path": "/categories/生活/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Java基础 categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/Java%E5%9F%BA%E7%A1%80/",
      "key": "v-fc6ed512",
      "path": "/categories/Java基础/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "smoothScroll": true,
    "authorAvatar": "/avatar.png",
    "lastUpdated": "2021-04-07",
    "author": "君哥",
    "startYear": "2022",
    "nav": [
      {
        "text": "本站指南",
        "link": "/guide/",
        "icon": "reco-eye"
      },
      {
        "text": "技术分享",
        "link": "/技术文章/",
        "icon": "reco-api",
        "items": [
          {
            "text": "Java",
            "items": [
              {
                "text": "JavaSE",
                "link": "/技术文章/java/javase"
              },
              {
                "text": "JavaEE",
                "link": "/技术文章/java高级/javaee"
              }
            ]
          },
          {
            "text": "前端",
            "items": [
              {
                "text": "前端基础",
                "link": "/技术文章/vue/vue01"
              }
            ]
          }
        ]
      },
      {
        "text": "生活分享",
        "link": "/生活分享/",
        "icon": "reco-faq",
        "items": [
          {
            "text": "生活分享",
            "link": "/生活分享/life"
          }
        ]
      },
      {
        "text": "博客",
        "icon": "reco-blog",
        "items": [
          {
            "text": "腾讯",
            "link": "https://how.ke.qq.com/",
            "icon": "reco-blog"
          },
          {
            "text": "B站",
            "link": "https://space.bilibili.com/394702492",
            "icon": "reco-bilibili"
          },
          {
            "text": "君哥",
            "link": "https://www.it235.com/",
            "icon": "reco-blog"
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2,
    "search": true,
    "searchMaxSuggestions": 10,
    "record": "沪ICP备xxxxx号-6",
    "recordLink": "https://beian.miit.gov.cn/",
    "cyberSecurityRecord": "沪公网安备 xxxxxxx号",
    "cyberSecurityLink": "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=xxx05177",
    "friendLink": [
      {
        "title": "君哥聊编程",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "xxx@qq.com",
        "link": "https://www.it235.com"
      },
      {
        "title": "君哥的课堂",
        "desc": "君哥的课堂",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://how.ke.qq.com/"
      }
    ]
  }
}