/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tags/ES6/",
      "pageKeys": [
        "v-00b78bfd",
        "v-6aa881d2"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tags/js/",
      "pageKeys": [
        "v-00b78bfd",
        "v-5b08735a",
        "v-6aa881d2",
        "v-24098ea5",
        "v-26f4ba23"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "tags",
      "path": "/tags/前端/",
      "pageKeys": [
        "v-00b78bfd",
        "v-5b08735a",
        "v-6aa881d2",
        "v-26f4ba23"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tags/vue/",
      "pageKeys": [
        "v-5b08735a",
        "v-24098ea5",
        "v-26f4ba23"
      ]
    },
    "Spring": {
      "key": "Spring",
      "scope": "tags",
      "path": "/tags/Spring/",
      "pageKeys": [
        "v-ca9a1562"
      ]
    },
    "SpringBoot": {
      "key": "SpringBoot",
      "scope": "tags",
      "path": "/tags/SpringBoot/",
      "pageKeys": [
        "v-ca9a1562"
      ]
    },
    "Java基础": {
      "key": "Java基础",
      "scope": "tags",
      "path": "/tags/Java基础/",
      "pageKeys": [
        "v-72c750ef"
      ]
    },
    "零基础": {
      "key": "零基础",
      "scope": "tags",
      "path": "/tags/零基础/",
      "pageKeys": [
        "v-72c750ef"
      ]
    },
    "生活": {
      "key": "生活",
      "scope": "tags",
      "path": "/tags/生活/",
      "pageKeys": [
        "v-472a77c8"
      ]
    },
    "分享生活": {
      "key": "分享生活",
      "scope": "tags",
      "path": "/tags/分享生活/",
      "pageKeys": [
        "v-472a77c8"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-00b78bfd",
        "v-5b08735a",
        "v-6aa881d2",
        "v-24098ea5"
      ]
    },
    "java": {
      "key": "java",
      "scope": "categories",
      "path": "/categories/java/",
      "pageKeys": [
        "v-ca9a1562"
      ]
    },
    "Java基础": {
      "key": "Java基础",
      "scope": "categories",
      "path": "/categories/Java基础/",
      "pageKeys": [
        "v-72c750ef"
      ]
    },
    "生活": {
      "key": "生活",
      "scope": "categories",
      "path": "/categories/生活/",
      "pageKeys": [
        "v-472a77c8"
      ]
    }
  },
  "timeline": {}
}