/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tags/ES6/",
      "pageKeys": [
        "v-0cce09a8",
        "v-ecede768"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tags/js/",
      "pageKeys": [
        "v-0cce09a8",
        "v-ecede768",
        "v-727310f7",
        "v-63acc4ea"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "tags",
      "path": "/tags/前端/",
      "pageKeys": [
        "v-0cce09a8",
        "v-3722c634",
        "v-ecede768",
        "v-727310f7",
        "v-63acc4ea"
      ]
    },
    "架构": {
      "key": "架构",
      "scope": "tags",
      "path": "/tags/架构/",
      "pageKeys": [
        "v-3722c634"
      ]
    },
    "mock": {
      "key": "mock",
      "scope": "tags",
      "path": "/tags/mock/",
      "pageKeys": [
        "v-3722c634"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tags/vue/",
      "pageKeys": [
        "v-727310f7",
        "v-63acc4ea"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-0cce09a8",
        "v-3722c634",
        "v-ecede768",
        "v-727310f7",
        "v-63acc4ea"
      ]
    }
  },
  "timeline": {}
}