/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "其他",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/其他/","interval":[0,3]}],
},
{
  pid: "tags",
  id: "入职随笔",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/入职随笔/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "ES6",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/ES6/","interval":[0,2]}],
},
{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/js/","interval":[0,4]}],
},
{
  pid: "tags",
  id: "前端",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/前端/","interval":[0,5]}],
},
{
  pid: "tags",
  id: "项目开发",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/项目开发/","interval":[0,2]}],
},
{
  pid: "tags",
  id: "架构",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/架构/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "mock",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/mock/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/vue/","interval":[0,2]}],
},
{
  pid: "categories",
  id: "其他",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/其他/","interval":[0,3]}],
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,5]}],
}]