/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "面向对象",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/面向对象/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "JavaSE",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/JavaSE/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/vue/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/js/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "生活",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/生活/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "分享生活",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/分享生活/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "Java基础",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/Java基础/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "零基础",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/零基础/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "Spring",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/Spring/","interval":[0,1]}],
},
{
  pid: "tags",
  id: "SpringBoot",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tags/SpringBoot/","interval":[0,1]}],
},
{
  pid: "categories",
  id: "java",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/java/","interval":[0,2]}],
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,1]}],
},
{
  pid: "categories",
  id: "生活",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/生活/","interval":[0,1]}],
},
{
  pid: "categories",
  id: "Java基础",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Java基础/","interval":[0,1]}],
}]